server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tfgdb}
    username: ${DB_USER:tfg}
    password: ${DB_PASSWORD:tfgpass}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
