package com.tfg.backend.Enums;

public enum AuditAction {
    CREATE_USER, UPDATE_USER, DELETE_USER, REGISTER_USER, VALIDATE_USER, VERIFY_USER_EMAIL,
    CREATE_OTO_CHAT, UPDATE_OTO_CHAT, DELETE_OTO_CHAT,
    CREATE_GROUP_CHAT, UPDATE_GROUP_CHAT, DELETE_GROUP_CHAT,
}
